# Основная информация
name: "Дневник ефу"
description: "Тир-лист с заметками"

# Тема-база
remote_theme: pages-themes/cayman

# Настройки сборки
sass:
  style: :compressed

exclude:
  - README.md
  - .gitignore

url: "https://efyo.ru"
baseurl: ""